
all: proposal.pdf

proposal.pdf: proposal.tex
	pdflatex proposal.tex
	pdflatex proposal.tex

deckBuilding.pdf: deckBuilding.tex
	pdflatex deckBuilding.tex
	pdflatex deckBuilding.tex

clean:
	rm -f *.aux *.log proposal.pdf deckBuilding.pdf

